version: "3.8"
services:
  redis:
    image: redis:7.2.4-alpine
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"

  app:
    image: 680950831771.dkr.ecr.ap-northeast-1.amazonaws.com/safety-kayak-fishing-api:latest
    working_dir: /myapp
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      RAILS_MASTER_KEY: 2ef7db76fea1adad51fa7ffec852b56d
      POSTGRES_HOST: safety-kayak-api-db.c8b65xuuo3fw.ap-northeast-1.rds.amazonaws.com
      POSTGRES_USER: haga
      POSTGRES_PASSWORD: 1123haga
      REDIS_URL: redis://redis:6379/0
      RAILS_ENV: production
    depends_on:
      - redis

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - etc/nginx/nginx.conf:/etc/nginx/nginx.conf # Nginxのメイン設定
      - etc/nginx/conf.d:/etc/nginx/conf.d # サーバーブロックの設定
      - /etc/letsencrypt:/etc/letsencrypt # SSL証明書
    depends_on:
      - app

volumes:
  redis-data:
