version: "3.8"
services:
  app:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./:/myapp
    working_dir: /myapp
    ports:
      - "3000:3000"
    depends_on:
      - redis
    environment:
      REDIS_URL: redis://redis:6379/0
      RAILS_ENV: test

  redis:
    image: redis:7.2.4-alpine
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"

volumes:
  redis-data:
