# PostgreSQL 
default: &default
  adapter: postgresql
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch('POSTGRES_USER', 'haga') %>
  password: <%= ENV.fetch('POSTGRES_PASSWORD', '1123haga') %>
  host: <%= ENV.fetch('POSTGRES_HOST', 'localhost') %>
  database: <%= ENV.fetch('POSTGRES_DB', 'myapp_development') %>
  port: <%= ENV.fetch('POSTGRES_PORT', 5432) %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
