# PostgreSQL
default: &default
  adapter: postgresql
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch('POSTGRES_USER', 'haga') %>
  password: <%= ENV.fetch('POSTGRES_PASSWORD', '1123haga') %>
  host: <%= ENV.fetch('POSTGRES_HOST', 'localhost') %>
  port: <%= ENV.fetch('POSTGRES_PORT', 5432) %>

development:
  <<: *default
  database: <%= ENV.fetch('POSTGRES_DB', 'myapp_development') %>

test:
  <<: *default
  database: <%= ENV.fetch('POSTGRES_DB', 'myapp_test') %>
  host: <%= ENV.fetch('POSTGRES_HOST', '127.0.0.1') %> # GitHubActionsのCI.yml で定義したサービス名

production:
  <<: *default
  database: <%= ENV.fetch('POSTGRES_DB', 'myapp_production') %>
