name: safety-kayak-fishing-api-ci
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello, World!"
