name: safety-kayak-fishing-api-ci

on:
  push:
    branches:
      - main # main ブランチへのプッシュ時に実行
  pull_request:
    branches:
      - main # main ブランチへのプルリクエスト時に実行

jobs:
  ci:
    runs-on: ubuntu-latest # ジョブは最新のUbuntuランナー上で実行される

    services:
      db:
        image: postgres:13 # 使用するPostgreSQLのDockerイメージ
        env:
          POSTGRES_USER: haga # PostgreSQLのユーザー名
          POSTGRES_PASSWORD: 1123haga # PostgreSQLのパスワード
          POSTGRES_DB: safety_kayak_fishing_api_test # テスト用のデータベース名
        ports:
          - 5432:5432 # ホストとコンテナ間で5432ポートをマッピング

    steps:
      - uses: actions/checkout@v2 # リポジトリのコードをチェックアウト

      - name: List directories
        run: ls -la

      - name: Set up Docker Compose
        # Docker Compose ファイルがあるディレクトリに移動
        # Docker Compose を使ってサービスをデタッチドモードで起動
        run: |
          cd safety-kayak-fishing-backend
          docker-compose -f docker-compose.yml up -d

      # データベースマイグレーションを実行
      - name: Prepare database
        run: |
          docker-compose exec app bundle exec rails db:migrate

      # RSpecを使ってテストを実行
      - name: Run tests
        run: |
          docker-compose exec app bundle exec rspec

      - name: Shutdown
        run: docker-compose down # すべてのサービスをシャットダウン
