version: "3.8"
services:
  app:
    build: ./safety-kayak-fishing-backend
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./safety-kayak-fishing-backend:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    environment:
      POSTGRES_HOST: db
      POSTGRES_USER: haga
      POSTGRES_PASSWORD: 1123haga
      REDIS_URL: redis://redis:6379/0

  redis:
    image: redis:7.2.4-alpine
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"

volumes:
  redis-data:
